# pandas import

# 1. series

## 1-1 series생성

--데이터(temp): 1월:-20, 2월:-10, 3월:10, 4월:20도  

- series의 온도만 보기  
- series의 월 만 보기  

인덱싱:
-    숫자로 2월 자료 꺼내오기->1,2,3월 다 가져오기  
-    이름으로 2월 자료 꺼내오기->1,2,3월 다 가져오기  
-    .loc, .iloc이용해서 위에꺼 가져오기
## - 역순으로 출력하기

값 추가:  
-    5월:30도 추가  
값 삭제:  
-    5월꺼 삭제->4,5월꺼 삭제  
-    적용 위해 필요한 문구는  
값 수정:  
-    5월꺼를 40도로

## - np.random함수로 series만들기
## - dict형태로 series만들고 인덱싱하기

## 1-2 series 연산

- temp series에 사칙연산 적용하면 어떻게 되는지  

인덱스가 다른 시리즈간의 연산:  
high=pd.Series([51500,51200,52500],index=['a','b','c'])  
low=pd.Series([50700,50500,50500],index=['a','b','d'])  
- 어떻게 될지 예측하고 실행

비교 연산:  
s=pd.Series([100,200,300,400,500])  
- s>300 실행하면 어떤식으로 나올지

- s는 300보다 큰애들만 나오게 필터링

---
---

# 2. dataframe

In [2]:
data = {
    '이름' : ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
    '학교' : ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
    '키' : [197, 184, 168, 187, 188, 202, 188, 190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기' : ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']
}
index=['1번','2번','3번','4번','5번','6번','7번','8번']
data

{'이름': ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
 '학교': ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
 '키': [197, 184, 168, 187, 188, 202, 188, 190],
 '국어': [90, 40, 80, 40, 15, 80, 55, 100],
 '영어': [85, 35, 75, 60, 20, 100, 65, 85],
 '수학': [100, 50, 70, 70, 10, 95, 45, 90],
 '과학': [95, 55, 80, 75, 35, 85, 40, 95],
 '사회': [85, 25, 75, 80, 10, 80, 35, 95],
 'SW특기': ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']}

- dic 형태의 data에서 이름 가져오기
- dic 형태의 data에서 키 가져오기

## 2-1 dataframe생성
- data로 df란 이름의 데이터프레임 만들기, row이름은 index데이터로 활용
- data에서 이름,학교,키자료들만 뽑아내서 df2만들기

- 밑의 자료로 열이름이 지정된 df3만들기    
이름 = ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협']  
학교 = ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고']  
키= [197, 184, 168, 187, 188, 202, 188, 190]  

- 밑의 자료로 열이름 지정된 df4만들기  
data = [
    ['채치수', '북산고', 197],
    ['정대만', '북산고', 184],
    ['송태섭', '북산고', 168],
    ['서태웅', '북산고', 187],
    ['강백호', '북산고', 188],
    ['변덕규', '능남고', 202],
    ['황태산', '능남고', 188],
    ['윤대협', '능남고', 190]
]

## 2-2 dataframe 인덱스

- df의 인덱스만 보여주는 함수
- df의 인덱스 이름을 '지원번호'로 바꾸기
- 인덱스 초기화 하기->지원번호 칸 자체를 없애는 옵션-> 실제로 적용시키기
- 인덱스를 컬럼의 이름 데이터로 새로 설정하고 실제로 적용
  
-  
- 여태 배운것을 통해 원 상태의 df로 되돌리기

## 2-3 파일 저장 및 열기
# -현재 파일 위치 함수
### 저장
밑에칸에 답 있음  
- df데이터를 score.csv로 저장하려면?  
- df를 score.txt로 저장
- score.xlse로 저장

정답  
- %pwd
- df.to_csv('score.csv',encoding='utf-8-sig',index=False)
- df.to_csv('score.txt',sep='\t')
- df.to_excel('score.xlsx')
# -그렇다면 index=True로 하면 결과는?


### false: df의 인덱스 포함X   vs  True: df의 인덱스 포함

### 열기
- score.csv열기
- score.csv열기
- score.xlsx열기

정답  
- df=pd.read_csv('score.csv')
- df = pd.read_csv('score.txt', sep='\t')
- df = pd.read_excel('score.xlsx')

### 열기 옵션
# -header=의 디폴트 값과 none의 의미는?
# -header=0 : 0번째인덱스(첫번째줄)을 컬럼으로
# -header=none이후 컬럼이름 지정방법(나중에 설정이 아닌 한줄에)
- 지정된 행 개수만큼 건너뛰는 옵션->특정 행만 건너뛰는 옵션
- 지정된 행 개수만 가져오는 옵션
- 인덱스 지정하는 옵션
- 원하는 열만 가져오는 옵션

---
- '지원번호'를 인덱스로 하여 score.xlsx를 df로

---

## 2-4 데이터 접근

### []
- df[]안에 들어갈 수 있는것은?
- []안에 True, False가 들어가면?
- df의 이름, 키 동시에 가져오기
- df의 컬럼이름을 모른다 가정할때 맨 뒤의 컬럼 데이터 가져오기  
- df[:] 형태로 하면 뽑아낼 수 있는것은
- 1행만 가져오기->2~4행 가져오기
- df의 이름, 키 데이터 중에서 4번선수 정보까지만 가져오기

### .loc
- 2번의 국어 점수 가져오기->2번의 모든 정보 가져오기
- 1번, 3번의 영어, 수학점수 가져오기
- 1번-5번 까지의 국어-사회 정보 가져오기
- 모든 행의 이름~과학 정보 가져오기
- df['']만 할 경우 들어갈 수 있는 정보와 나오는 결과는?

### .iloc
- df.iloc[] 하나일때 안에 들어갈 수 있는 정보와 나오는 결과는?
- 1번, 3번 학생의 학교~과학까지의 정보만 가져오기

### filtering
- 키 185이상인 학생의 모든 정보 가져오기(df[]를 사용해서)->185미만 가져오기
- 키 185이상인 학생의 이름,수학,과학 정보 가져오기(.loc을 사용해서)
- 키가 185 이상이면서 북산고 학생 데이터 가져오기
- 키가 170 보다 작거나 or 200 보다 큰 학생 데이터

### 문자열 처리, 비교
- 송으로 시작하는 사람의 모든 정보 가져오기
- 이름에 태가 들어간 사람의 모든 정보 가져오기
- langs = ["Python", "Java"] 에대해 SW특기가 lang안에 들어간 애들 가져오기
- langs = ["python", "java"] (소문자)일 경우 가져오기
- SW특기에 Java단어를 포함한 애들 가져오기
## 날짜형데이터의 인덱싱
cospi.csv 이용-> Date 날짜화 후 인덱스로
- 2016년도 인덱싱-> 2016년도 2월만 인덱싱 -> 2016년도 1~2월 범위로 가져오기 
- n일 단위 평균 계산하기-> High컬럼에 대한 5일치 평균으로 새로운 열-> 그냥과 5일치를 시각화하기

## 2-5 데이터 플레임에서 결측치 처리

- NaN을 hi로 채우기(적용은X)
- 학교를 np.nan을 통해 NaN으로 바꾸고 SW특기만 결측치 hi로 바꾸기
- 결측치 들어간 행 지우기->두가지 종류
- 결측치 들어간 열 지우기->두가지 종류

## 2-6 데이터 정렬

- 인덱스에 따라 정렬(오름차순, 내림차순)
- 키에 따라 정렬
- 우선 수학을 기준으로 정렬-> 값이 같으면 그 다음 영어를 기준으로 정렬->수학 점수는 오름차순으로, 영어 점수는 내림차순으로 정렬
- 키 시리즈 안에서 정렬

## 2-7 데이터 수정
### 컬럼 수정
- 전체 데이터에서 북산고->상북고, 능남고->무슨고로 변경
- 학교 컬럼에서 북산고->상북고, 능남고->무슨고로 변경
- SW특기의 데이터를 전부 소문자로 변경
- 학교 데이터에 등학교 붙이기
### 컬럼 추가,삭제
- 국어+영어+수학+과학+사회를 다 더한 '총합' 이란 새로운 컬럼 생성
- '결과' 란 새로운 컬럼 만들고 총합이 400 이상이면 결과열을 pass로, 나머지는 fail
- 총합, 결과 컬럼 삭제
### 열 추가, 삭제
- 9번: '이정환', '해남고등학교', 184, 90, 90, 90, 90, 90, 'Kotlin', 450, 'Pass' 정보로 새로운 행 추가
- 9번 행 삭제
- 수학 80점 밑인 애들 지우기
### cell 수정
- 서태웅의 sw특기를 파이썬으로 수정해보기
- 1번,3번의 이름,키를 aa,bb와 1,2로 수정해보기
### 컬럼 변경
- 원래의 이름-결과를 이름,총합,결과,학교-SW특기로 바꾸기
- SW특기 컬럼이름을 sw로 바꾸기
- 이름 데이터를 두칸 내린 새로운 'hi'컬럼 만들기
- 키 데이터를 3칸 올린 새로운 'bye'컬럼 만들기

## 2-8 데이터프레임에서 함수 사용
### df전체
- 계산 가능한 데이터에 대해 column별로 데이터의 갯수, 평균, 표준편차, 최소/최대값 등의 정보를 보여주는 함수
- 각 데이터가 어떤 타입인지 보여주는 함수(int인지 object인지 등)
- 처음 앞부분의 행을 가지고 오는 함수
- 뒷부분 행 가져오는 함수
- 각 행의 정보들을 하나의 리스트로 묶어 가져오는 함수
- df의 인덱스를 가져오는 함수
- df의 컬럼 이름을 가져오는 함수
- df가 몇행 몇열인지 알려주는 함수

### df의 series에서
- 키에 대한 정보요약 함수 사용하기
- 키의 최솟값은?
- 키큰사람 순서대로 3명 데이터
- 키 평균 구하기
- 모든 키의 함 구하기
- SW특기 개수 세기
- 중복없이 학교 정보 보여주는 함수
- 학교의 고유값이 몇개인지 보여주는 함수

## - 키 자료끝에 cm붙이기

### 그룹화-> 그룹을 인덱스화
- 학교로 그룹화 하고 북산고 자료만 가져오기
- 학교에 따른 계산 가능한 데이터들의 평균값
- 학교로 그룹화 했을때 각 그룹의 크기
- 학교로 그룹화 했을때 모든 컬럼의 데이터 개수  
- 학교에 따른 국어, 영어, 수학 각각의 평균값

df['학년'] = [3, 3, 2, 1, 1, 3, 2, 2] # 학년 Column 추가  

- 학년 별 계산가능한 자료들의 평균->이 중 수학 점수에 따라 정렬  
- 학교 별, 학년 별 계산가능한 자료들의 평균
- 학교별, 학년별 그룹 개수
- 학교로 그룹화 한 다음 이중 각 학년 별 학생 수는?->비율로 나타내기->여기서 북산고 애들만 꺼내오기

# 2-9 extra
- df['키']를 리스트로 
- df를 1차원화했다고 다시 원상태로
- df 행/열 바꾸기
- df int타입에서 각 행/열 별로 sum집계함수+100해주는 함수 적용시키기
- 모든 df요소에 '!'문자 붙이는 함수 적용시키기

# 2-10 바로 시각화
- 아무런 파라미터도 지정안하고 실행하면? x값에는 뭐가오는지? y값에는 뭐가오는지?
- x값을 지정하면 뭐가 나오는지------------------------------------------------------------x컬럼의 모든값이 x축에 있게됨
- 어떤 데이터로 원형차트 그릴수 있는지-> 그걸로 그려보기
- 학년별 모든 numeric데이터를 막대차트로 그리면?
- 키를 히스토그램으로 나타내기
- 국어점수에따른 수학점수를 나타내는 스캐터그리기(학년을 기준화하여)
- x,y사용안하고 수학,과학점수를 기본그래프로 시각화  
/  
- from pandas.plotting import scatter_matrix 로 수치형자료넣어 nXn plot보기

# -추가 groupby
---
---
---
----group by---- : ___그룹 고유값을 인덱스로 두겠다___   
주로 범주형을 하나 또는 여러개 그룹화(수치형도 가능하긴함)

df.groupby([col1,col2,...,coln])은 인덱스에 왼쪽부터 col1,col2,...,coln순으로 나옴

df.groupby후 표로 나타낼려면 .get_group말고는 전부 집계함수써야함(count, max, sum등) 

groupby후 .agg(['mean','sum'])처럼 집계함수 여러개 사용가능-> 각 변수당 함수개수만큼 컬럼개수로 늘어남 

!!!반드시 그룹바이 후 집계함수 사용된 이후여야 .plot가능!!!   
!!! x에는 모든 인덱스가(그룹,다중그룹이면 튜플로 표시) y에는 요소값이, 그리고 각 컬럼별로 레이블 됨 !!!  
	-> y지정안하면 모든 컬럼의 요소들이 전부 표시, .pie할때는 y컬럼 하나만 가능

---
---
---
data={'name':['a','b','a','b','d','c','d','d','c','a','a','v','e','d','b','b'],
      'value':[1,5,3,8,4,6,4,8,3,10,34,1,8,5,7,9]}  
g=pd.DataFrame(data)  
- name으로 그룹화하고 각 name값 개수들을 세어 counts라는 새로운 컬럼 생성(한줄식으로 인덱스(0~5),컬럼(name,counts)이 전부생성되게)
- counts를 기준으로 정렬
- 그룹화 후 value에 대해 그룹함수 함수이름과 min, sum등 사용해보기

# 2-11 groupby 시각화
- wine10.csv를 불러와 type과 quality로 그룹화하고 mean과 sum 집계함수 동시 사용
- 바로 시각화: 위의 그룹 x에 오는 데이터는? y에 오는 데이터는? ->y설정하면? -> pH와 citric acid컬럼설정  
-> kind를 line이나 bar로 할때하고 box로 할때 작동방식 차이 확인
- 종류 다보기: 기본, 막대, 히스토그램, 히스토그램 선형화버전, 막대상자, 원형
- wine에서 type별, quality별 ph, alcohol, citric acid의 최대값들을 시각화하면?

# 2-12 카이제곱표 만들기
data = pd.DataFrame({
    '성별': ['남', '여', '남', '여', '남'],
    '흡연': ['예', '아니오', '예', '아니오', '아니오'],
    '나이': [25, 30, 27, 22, 35]})
- 성별, 흡연에 따른 개수
- 나이값이 들어갈려면 어떤식으로 들어가는지

# 2-13 데이터프레임 합치기
### 두가지 방법
a={'a':[1,2,3],'b':[4,5,6]}  
b={'a':[7,8,9],'b':[10,11,12]}  
adf=pd.DataFrame(a)  
bdf=pd.DataFrame(b)  
- 첫번째 방법으로 위의 adf,bdf 합치기 두가지 경우
  
a={'a':[1,2,3],'b':[4,5,6]}  
b={'a':[1,3,9],'c':[10,11,12]}  
adf=pd.DataFrame(a)  
bdf=pd.DataFrame(b)
- 두번째 방법의 parameter들 종류와 'a'컬럼기준으로 4가지 종류로 합치기
- 또 다른 방법 하나 더

# 2-14 행과 열 회전
### 두가지 방법과 차이
data={'name':['a','b','a','b','d','c','d','d','c','a','a','v','e','d','b','b'],
      'value':[1,5,3,8,4,6,4,8,3,10,34,1,8,5,7,9],
     'sex':['f','f','f','f','f','f','f','f','m','m','m','m','m','m','m','m']}  
g=pd.DataFrame(data)  
- 첫번째 방법의 파라미터는?
- sex를 인덱스, name을 컬럼으로, 이름의 고유 개수들을 데이터값으로

- 두번째 방식으로 인덱스에 sex, 컬럼에 name, 데이터 값으로 value들의 그룹별 합으로 나타내기
- 이 후 total이라는 새로운 컬럼 만들어 각 행의 총합 값 집어넣기
# 추가
wine10.csv사용
- 인덱스로  type만 선택하면 나오는 값은?
- 컬럼스에 들어갈만한 값은? ---------------------------------------범주형값-> 그 값을 컬럼으로, 그 그룹별 최솟값  
-> 그러면 나오는 컬럼스 값들은? -> 컬럼값의 고유값들에 속하는 알코올의 최솟값 보기
- 인덱스로 type, quality만 두고 나머지 칼럼의 최대값 보기